api:
  tty: true
  restart: always
  build: api/
  expose:
    - "8000"
  links:
    - postgres:postgres
  volumes:
    - /app
  env_file: .env
  environment:
    DEBUG: 'true'
  ports:
    - "8000:8000"

web:
  tty: true
  restart: always
  build: web/
  expose:
    - "3000"
  links:
    - api:api
  volumes:
    - /usr/src/app
  env_file: .env
  environment:
    - HOST=0.0.0.0
  ports:
    - "3000:3000"
    
postgres:
  restart: always
  build: ./api/postgres/
  ports:
    - "5432:5432"
  volumes:
    - pgdata:/var/lib/postgresql/data/



