version: '2'

services:
  test:
    volumes:
      - ./test:/go/src/test

    working_dir: /go/src/test
    build: ./test

    links:
        - transaction:transaction
        - quote_server_mock:quoteserver

    depends_on:
      - transaction

    environment:
      - TRANS_HOST=transaction
      - TRANS_PORT=8888
      - QUOTE_SERVER_HOST=quoteserver
      - QUOTE_SERVER_PORT=8000


  db:
    build: ./postgres

    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - "5432:5432"


  quote_server_mock:
    volumes:
      - ./quote_server_mock:/go/src/quote_server_mock

    working_dir: /go/src/quote_server_mock

    build: ./quote_server_mock

    entrypoint: go run app.go

    ports:
      - "8000:8000"

    environment:
      - QUOTE_SERVER_PORT=8000


  transaction:

    volumes:
      - ./transaction_service:/go/src/transaction_service

    working_dir: /go/src/transaction_service

    build: ./transaction_service

    ports:
      - "8888:8888"

    depends_on:
      - db

    links:
        - db:database
        - quote_server_mock:quoteserver

    entrypoint: waitforit -address=tcp://database:5432 -timeout=20 -debug -- go run app.go

    command: go run app.go


    environment:
      - POSTGRES_HOST=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=transactions
      - DB_PORT=5432
      - QUOTE_SERVER_HOST=quoteserver
      - QUOTE_SERVER_PORT=8000

