version: '2'

services:
  test:
    volumes:
      - ./test:/go/src/test
      - ./common:/go/src/common

    working_dir: /go/src/test

    build:
      context: .
      dockerfile: test/Dockerfile

    links:
        - transaction:transaction
        - quote_server_mock:quoteserver

    depends_on:
      - transaction

    env_file:
      - vars.env

  log_db:
    build: ./log_db

    volumes:
      - ./log_db/init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - "5433:5432"

  transaction_db:
    build: ./transaction_db

    volumes:
      - ./transaction_db/init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - "5432:5432"

  redis:
    build: ./redis

    ports:
      - "6379:6379"

    env_file:
      - vars.env

  rabbit:
    build: ./rabbit
    
    ports:
      - "15672:15672"

    env_file:
      - vars.env
    
  quote_server_mock:
    volumes:
      - ./quote_server_mock:/go/src/quote_server_mock
      - ./common:/go/src/common

    working_dir: /go/src/quote_server_mock

    build: ./quote_server_mock

    entrypoint: fresh app.go

    ports:
      - "8000:8000"

    env_file:
      - vars.env

  transaction:

    volumes:
      - ./transaction_service:/go/src/transaction_service
      - ./common:/go/src/common

    working_dir: /go/src/transaction_service

    build:
      context: .
      dockerfile: transaction_service/Dockerfile
    
    ports:
      - "8888:8888"

    depends_on:
      - transaction_db
      - rabbit
      - redis

    links:
        - transaction_db:transdb
        - quote_server_mock:quoteserver
        - redis:redis
  
    entrypoint: waitforit -address=tcp://transdb:5432 -timeout=20 -debug -- waitforit -address=tcp://redis:6379 -timeout=20 -debug -- waitforit -address=tcp://rabbit:5672 -timeout=20 -debug -- fresh app.go

    command: go run app.go

    env_file:
      - vars.env