version: '3'

services:
  test:
    volumes:
      - ./test:/go/src/test

    working_dir: /go/src/test
    build: ./test

    links:
        - transaction:transaction
        - quote_server_mock:quoteserver

    depends_on:
      - transaction

    environment:
      - TRANS_HOST=transaction
      - TRANS_PORT=8888
      - QUOTE_SERVER_HOST=quoteserver
      - QUOTE_SERVER_PORT=8000
